[package]
name = "pq12p_actuator"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-stm32 = { version = "0.4.0", features = [
    "stm32g474re",
    "unstable-pac",
    "single-bank",
] }
embassy-time = "0.5.0"
