[package]
name = "hrtim_pwm_hal"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-stm32 = { version = "0.5.0", features = [
    "memory-x",
    "single-bank",
    "stm32g474re",
    "time-driver-any",
    "exti",
    "unstable-pac",
] }
paste = "1.0.15"
